<div class="firecheckout-header">
    <?php
        $logo2x = false;
        if (Mage::helper('core')->isModuleOutputEnabled('TM_Argento')) :
            $logo2x = Mage::helper('argento')->getLogo2xSrc();
        endif;
    ?>
    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="firecheckout-logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" <?php echo $logo2x ? " srcset='{$this->getLogoSrc()} 1x, {$logo2x} 2x'" : '' ?> alt="<?php echo $this->getLogoAlt() ?>" /></a>
</div>
