<?php if (Mage::getSingleton('customer/session')->isLoggedIn()): return; endif; ?>
<div id="firecheckout-login-window" class="firecheckout-set" style="display: none;">
    <div class="fc-window-title">
        <span><?php echo $this->__('Login into your Account') ?></span>
    </div>
    <form action="<?php echo $this->getUrl('*/*/login', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on'))) ?>" method="post" id="firecheckout-login-form">
        <div class="content">
            <ul class="form-list">
                <li class="wide">
                    <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                    </div>
                </li>
                <li class="wide">
                    <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                        <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="link-forgot-password" title="<?php echo $this->__('Forgot your password?') ?>"><?php echo $this->__('Forgot?') ?></a>
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </div>
        <div class="buttons-set">
            <button type="submit" class="button btn-hero" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var loginForm = new VarienForm('firecheckout-login-form', true);

        $$('#firecheckout-login-window .link-forgot-password').each(function(el) {
            el.observe('click', function(e) {
                Event.stop(e);
                var email = $('email'),
                    messageContainer = $('firecheckout-login-form');

                FC.ForgotPassword.forgot(email, messageContainer, el);
            });
        });
    //]]>
    </script>
</div>