<div class="form-list" id="payex-ssn-number">
    <div id="ssn-error-placeholder" class="field" style="display: none">
        <ul class="messages">
            <li class="error-msg">
                <ul>
                    <li>
                        <span id="ssn-error">&nbsp;</span>
                    </li>
                </ul>
            </li>
        </ul>
    </div>

    <div class="field">
        <label for="socialSecurityNumber" class="required"><em>*</em><?php echo Mage::helper('payex')->__('Social Security Number'); ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo Mage::helper('payex')->__('Social Security Number'); ?>" name="socialSecurityNumber" id="socialSecurityNumber" class="input-text required-entry" />
        </div>
    </div>
    <div class="clearer">&nbsp;</div>

    <div id="ssn_details" style="display: none">
        <div class="field">
            <strong><?php echo Mage::helper('payex')->__('Please enter additional fields:'); ?></strong>
        </div>
        <div class="clearer">&nbsp;</div>
        <div class="field">
            <div class="field_left">
                <div class="input-box">
                    <label for="check_country" class="required"><em>*</em><?php echo Mage::helper('payex')->__('Country'); ?></label>
                    <select name="check_country" id="check_country" class="validate-select required-entry" title="Country">
                        <option value="SE" selected="selected"><?php echo Mage::helper('payex')->__('Sweden'); ?></option>
                        <option value="NO"><?php echo Mage::helper('payex')->__('Norway'); ?></option>
                    </select>
                </div>
            </div>

            <div class="field_right">
                <div class="input-box">
                    <label for="check_postcode" class="required"><em>*</em><?php echo Mage::helper('payex')->__('Postal Code'); ?></label>
                    <input type="text" title="<?php echo Mage::helper('payex')->__('Postal Code'); ?>" name="check_postcode" id="check_postcode" class="input-text validate-zip required-entry" />
                </div>
            </div>
        </div>
    </div>

    <div class="field">
        <button type="button" title="<?php echo Mage::helper('payex')->__('Get Address'); ?>" class="button" id="ssn_click"><span><span><?php echo Mage::helper('payex')->__('Get Address'); ?></span></span></button>
    </div>

    <div class="clearer">&nbsp;</div>
    <script>
        //<![CDATA[
        var MAGENTO_BASE_URL = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true); ?>';
        window.PAYEX_SSN_FORM = new VarienForm('payex-ssn-number', false);
        //]]>
    </script>
</div>
