<!--gift card section-->
<?php if(!Mage::getStoreConfig('giftcards/default/show_as_payment_method')): return; endif; ?>

<?php $oGiftCardSession = Mage::getSingleton('giftcards/session'); ?>
<div id="giftcard-section" class="firecheckout-section">
    <div class="block-title"><span><?php echo $this->__('Gift Card'); ?></span></div>
    <div class="discount-form">
        <div class="input-box">
            <div class="input-field-wrapper">
                <input value="" name="giftcard_code" id="giftcard_code" class="input-text">
            </div>
            <button id="giftcard-add" value="<?php echo $this->__('Apply') ?>" onclick="activateGiftCard.save()" class="button"
                    title="Apply" type="button" style="float: left;"><span><span><?php echo $this->__('Apply') ?></span></span>
            </button>
        </div>

        <?php
            $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
            $temp = 0;
        ?>
        <?php
            foreach($oGiftCardSession->getFrontOptions() as $k => $v) {
                if($temp) {
                    echo '<br/><br/>';
                }
                echo '<b>'.$currencySymbol.$v['applied'].$this->__('applied from Gift Card').' **********'.$v['code'].'.</b><br/>';
                echo $this->__('Remaining card balance').': '.$currencySymbol.$v['remaining'].'. (<a href="#" onclick="deActivateGiftCard.deactivate('.$k.');">'.$this->__('Remove').'</a>)';
                $temp = 1;
            }
        ?>
    </div>
</div>
<!-- end gift card section-->
