<?php if ($this->getQuote()->isVirtual() || !Mage::getStoreConfig('firecheckout/general/shipping_address')) : return; endif; ?>
<ul class="form-list">
    <li class="control">
        <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Ship to the same address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" /><label for="shipping:same_as_billing"><?php echo $this->__('Ship to the same address') ?></label>
    </li>
</ul>

<?php
    $_address = $this->getAddress();
    $_prefix  = 'shipping';
    $fields   = array(
        'name'    => array(),
        'company' => array(
            'class' => 'input-text',
            'label' => 'Company'
        ),
        'fax' => array(
            'class' => 'input-text',
            'type'  => 'tel',
            'label' => 'Fax'
        ),
        'telephone' => array(
            'class' => 'input-text',
            'type'  => 'tel',
            'label' => 'Telephone'
        ),
        'city' => array(
            'class' => 'input-text',
            'label' => 'City'
        ),
        'postcode' => array(
            'class' => 'input-text validate-zip-international',
            'label' => 'Zip/Postal Code'
        ),
        'street1' => array(
            'class' => 'input-text',
            'label' => 'Address',
            'title' => 'Street Address',
            'name'  => $_prefix . '[street][]',
            'value' => $_address->getStreet(1)
        ),
        'country_id' => array(
            'label' => 'Country',
            'required_to_render' => 1
        ),
        'region' => array(
            'label' => 'State/Province',
            'required_to_render' => 1
        )
    );

    $addressHelper = $this->helper('customer/address');
    if (method_exists($addressHelper, 'isVatAttributeVisible')
        && $addressHelper->isVatAttributeVisible()) {

        $fields['vat_id'] = array(
            'status' => 'optional',
            'class'  => 'input-text ' . $addressHelper->getAttributeValidationClass('vat_id'),
            'label'  => 'VAT Number'
        );
    }

    // ability to disable fields programmatically from layout xml update
    $disabledFields = $this->getDisabledFields() ? $this->getDisabledFields() : array();
    $fields = array_diff_key($fields, $this->getDisabledFields());
?>

<div id="shipping-address"<?php if($this->getAddress()->getSameAsBilling()): ?> style="display: none;"<?php endif; ?>>
    <div class="block-title"><span><?php echo $this->__('Shipping Address') ?></span></div>
    <div class="block-content">
        <ul class="form-list">
        <?php if ($this->customerHasAddresses()): ?>
           <li class="wide">
               <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
               <div class="input-box">
                   <?php echo $this->getAddressesHtmlSelect('shipping') ?>
               </div>
           </li>
        <?php endif ?>
            <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
                <fieldset>
                    <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                    <ul>
                        <?php foreach (Mage::helper('firecheckout/address')->getRows($fields) as $row) : ?>
                            <?php
                                $_isMulticolumn = $row->getIsMulticolumn();
                                $className = $_isMulticolumn ? 'fields' : 'wide';
                                $style = $row->getIsVisible() ? '' : ' style="display: none;"';
                            ?>

                            <?php if (in_array('company', $row)) : ?>
                                <?php echo $this->getLayout()->createBlock('firecheckout/checkout_shipping')->setTemplate('tm/firecheckout/taxidpro/shipping_fields.phtml')->toHtml() ?>
                                <?php continue; ?>
                            <?php endif; ?>

                            <li class="<?php echo $className ?>"<?php echo $style ?>>
                                <?php foreach ($row->getFields() as $field => $config) : ?>
                                    <?php $required = ('required' === $config['status']); ?>

                                    <?php if ('name' === $field) : ?>
                                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($_address)->setFieldIdFormat($_prefix . ':%s')->setFieldNameFormat($_prefix . '[%s]')->toHtml() ?>
                                        <?php continue; ?>
                                    <?php endif; ?>

                                    <?php if ('hidden' === $config['status']) : ?>
                                        <div style="display:none">
                                    <?php endif ?>

                                    <?php if ($_isMulticolumn) : ?>
                                        <div class="field">
                                    <?php endif ?>

                                    <label for="<?php echo $_prefix ?>:<?php echo $field ?>"
                                        class="<?php echo $required ? 'required' : '' ?>"
                                        ><?php if ($required): ?><em>*</em><?php endif; ?><?php echo $this->__($config['label']) ?></label>
                                    <div class="input-box">
                                        <?php if ('country_id' === $field) : ?>
                                            <?php echo $this->getCountryHtmlSelect($_prefix) ?>
                                        <?php elseif ('region' === $field): ?>
                                            <select id="<?php echo $_prefix ?>:region_id" name="<?php echo $_prefix ?>[region_id]"
                                                title="<?php echo (empty($config['title']) ? $this->__($config['label']) : $this->__($config['title'])) ?>"
                                                class="validate-select<?php echo $required ? ' required-entry' : '' ?>" style="display:none;"
                                            >
                                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                            </select>
                                            <script type="text/javascript">
                                            //<![CDATA[
                                                $('<?php echo $_prefix ?>:region_id').setAttribute('defaultValue',  "<?php echo $_address->getRegionId() ?>");
                                            //]]>
                                            </script>
                                            <input type="text" id="<?php echo $_prefix ?>:region" name="<?php echo $_prefix ?>[region]"
                                                value="<?php echo $this->htmlEscape($_address->getRegion()) ?>"
                                                title="<?php echo (empty($config['title']) ? $this->__($config['label']) : $this->__($config['title'])) ?>"
                                                class="input-text<?php echo $required ? ' required-entry' : '' ?>" style="display:none;"
                                            />
                                        <?php else: ?>
                                            <?php
                                                if (isset($config['value'])):
                                                    $value = $config['value'];
                                                else:
                                                    $method = 'get' . ucfirst($field);
                                                    $value = $_address->{$method}();
                                                endif;
                                            ?>
                                            <input type="text"
                                                name="<?php echo (empty($config['name']) ? $_prefix . '[' . $field . ']' : $config['name']) ?>"
                                                id="<?php echo $_prefix ?>:<?php echo $field ?>"
                                                value="<?php echo $this->htmlEscape($value) ?>"
                                                title="<?php echo (empty($config['title']) ? $this->__($config['label']) : $this->__($config['title'])) ?>"
                                                class="<?php echo $config['class'] ?><?php echo $required ? ' required-entry' : '' ?>"
                                            />
                                        <?php endif ?>
                                    </div>

                                    <?php if ($isMulticolumn) : ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ('hidden' === $config['status']) : ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ('street1' === $field) : ?>
                                        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                            </li>
                                            <li class="wide">
                                                <div class="input-box">
                                                    <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="<?php echo $_prefix ?>[street][]" id="<?php echo $_prefix ?>:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($_address->getStreet($_i)) ?>" class="input-text" />
                                                </div>
                                        <?php endfor ?>
                                    <?php endif; ?>

                                <?php endforeach ?>
                            </li>
                        <?php endforeach; ?>

                    <?php $addressAttributes = $this->getChild('customer_form_' . $_prefix . '_address_user_defined_attributes');?>
                    <?php if ($addressAttributes): ?>
                        <?php $addressAttributes->setEntity($_address)->setEntityType('customer_address');?>
                        <?php $addressAttributes->setFieldIdFormat($_prefix . ':%1$s')->setFieldNameFormat($_prefix . '[%1$s]');?>
                        <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
                    <?php endif;?>

                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                        <li class="control">
                            <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" <?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></li>
                    <?php else:?>
                        <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                    <?php endif;?>

                    <?php $additional = $this->getChildHtml('shipping.additional.container');
                    if (!empty($additional)) : ?>
                        <li class="shipping-additional">
                            <?php echo $additional; ?>
                        </li>
                    <?php endif; ?>
                    </ul>
                </fieldset>
            </li>
        </ul>
        <script type="text/javascript">
        //<![CDATA[
            var shipping = new Shipping('firecheckout-form');
            var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
        //]]>
        </script>
    </div>
</div>