<?php
$_agreements = $this->getAgreements();
if (!count($_agreements)) {
    return;
}
?>

<?php $outputType = Mage::getStoreConfig('firecheckout/agreements/output'); ?>
<ol class="checkout-agreements">
<?php $_i = 0; foreach ($_agreements as $_a): ?>
    <li<?php echo ++$_i === count($_agreements) ? ' class="last"' : ''?>>
        <div id="firecheckout-agreement-<?php echo $_a->getId() ?>-window"
            class="agreement-content"
            style="<?php echo 'minimal' === $outputType ? 'display: none;' : ($_a->getContentHeight() ? 'height:' . $_a->getContentHeight() : '') ?>"
        >
            <?php if ('minimal' === $outputType) : ?>
                <div class="fc-window-title">
                    <span><?php echo $this->htmlEscape($_a->getName()) ?></span>
                </div>
            <?php endif; ?>
            <?php if ($_a->getIsHtml()):?>
                <?php echo $_a->getContent() ?>
            <?php else:?>
                <?php echo nl2br($this->htmlEscape($_a->getContent())) ?>
            <?php endif; ?>
        </div>
        <p class="agree">
            <input type="checkbox"
                id="agreement-<?php echo $_a->getId()?>"
                name="agreement[<?php echo $_a->getId()?>]"
                value="1"
                title="<?php echo $this->htmlEscape($_a->getCheckboxText()) ?>"
                class="checkbox"
            />
            <label for="agreement-<?php echo $_a->getId()?>"
                class="firecheckout-agreement-label-<?php echo $outputType ?> firecheckout-agreement-<?php echo $_a->getId() ?>"
                data-agreement="firecheckout-agreement-<?php echo $_a->getId() ?>"
            ><?php echo $_a->getCheckboxText() ?></label>
        </p>
    </li>
<?php endforeach ?>
</ol>

<?php if ('minimal' === $outputType) : ?>
<?php $agreeText = $this->__(Mage::getStoreConfig('firecheckout/agreements/agree_text')); ?>

<script>
if (typeof firecheckoutAgreementsWindow === 'object') {
    if (firecheckoutAgreementsWindow.window) {
        // @todo: write proper destruct method
        firecheckoutAgreementsWindow.window.remove();
    }
}
var triggers = {};
$$('.firecheckout-agreement-label-minimal').each(function(el) {
    var agreement = el.readAttribute('data-agreement');
    triggers[agreement] = {
        el    : $$('.' + agreement),
        event : 'click',
        window: $(agreement + '-window'),
        actionbar: {
            hidden: <?php echo (int)empty($agreeText) ?>,
            html: '<label class="btn-agree" id="' + agreement + '-button">'
                + "<?php echo $agreeText ?>"
                + '</label>',
            el: agreement + '-button',
            event: 'click',
            callback: function(e, id) {
                // prevent if inner link was clicked
                if (e.element().tagName === 'A') {
                    return;
                }

                if (typeof event != 'undefined') { // ie9 fix
                    event.preventDefault ? event.preventDefault() : event.returnValue = false;
                }
                e.stop();
                $(id).checked = 'checked';
                this.hide();
            }
        }
    };
});
firecheckoutAgreementsWindow = new FC.Window({
    triggers: triggers
});
</script>
<?php endif; ?>
