<?php
    $successBlock = $this->getSuccessBlock();
?>

<div class="thank-you-note">

<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 130.2 130.2" class="check-mark">
    <circle class="path circle" fill="none" stroke-miterlimit="10" cx="65.1" cy="65.1" r="62.1"></circle>
    <polyline class="path check" fill="none" stroke-linecap="round" stroke-miterlimit="10" points="100.2,40.2 51.5,88.8 29.8,67.5 "></polyline>
</svg>

<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>

<?php if ($successBlock->getOrderId()):?>
    <p><?php echo $this->__('You will receive an order confirmation email with details of your order.') ?></p>

    <?php if ($successBlock->getCanViewOrder()) :?>
        <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($successBlock->getViewOrderUrl()), $this->escapeHtml($successBlock->getOrderId()))) ?></p>
    <?php  else :?>
        <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($successBlock->getOrderId())) ?></p>
    <?php endif;?>

    <?php if ($successBlock->getCanViewOrder() && $successBlock->getCanPrintOrder()) :?>
        <p>
            <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $successBlock->getPrintUrl()) ?>
        </p>
    <?php endif;?>
<?php endif;?>

<?php if ($profiles = $successBlock->getRecurringProfiles()):?>
    <p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
    <ul class="disc">
    <?php foreach($profiles as $profile):?>
    <?php $profileIdHtml = ($successBlock->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($successBlock->getProfileUrl($profile)), $this->escapeHtml($successBlock->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($successBlock->getObjectData($profile, 'reference_id')));?>
        <li><p><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($successBlock->getObjectData($profile, 'schedule_description')))?></p></li>
    <?php endforeach;?>
    </ul>
<?php endif;?>

    <p class="continue-shopping"><a href="<?php echo $this->getUrl() ?>"><?php echo $this->__('Continue Shopping') ?></a></p>

</div>
