<?php
    $validator = $this->getValidator();
    $addresses = $validator->getAddresses();
    $count     = count($addresses);
?>

<?php if ($this->canUseZipAutocorrection()) : ?>
    <script type="text/javascript">
        //<![CDATA[
        addressVerification = new FC.AddressVerification();
        addressVerification.autocorrectAddresses(<?php echo $this->getVerifiedAddressesJson();?>);
        //]]>
    </script>
    <?php return; ?>
<?php endif; ?>

<div id="address-verification-window" style="display: none;">
    <div class="fc-window-title">
        <span><?php echo $this->__('Address verification') ?></span>
    </div>
    <?php if ($error = $validator->getError()) : ?>
        <ul class="messages">
            <li class="error-msg">
                <?php echo $this->escapeHtml($error); ?>
            </li>
        </ul>
    <?php else : ?>
        <p class="verification-note"><?php echo $this->__(
            'Address could not be verified. Please double check the address before submitting the order. If the address is correct, just place the order without making any changes to it.'
        ) ?></p>
    <?php endif; ?>

    <?php foreach ($addresses as $type => $addressData) :
        $verifiedAddresses = $validator->getVerifiedAddresses($type);
        if (!$verifiedAddresses || $validator->isVerified($type)) :
            continue;
        endif;
    ?>
        <div class="content verification-<?php echo $type ?>">
            <?php if (2 === $count) : ?>
                <p class="address-verification-title"><?php echo $this->getTitle($type) ?></p>
            <?php endif; ?>

            <?php if ($error = $validator->getAddressError($type)) : ?>
                <ul class="messages">
                    <li class="error-msg">
                        <?php echo $this->escapeHtml($error); ?>
                    </li>
                </ul>
            <?php endif; ?>
            <ul class="address-actions">
                <li>
                    <input type="radio" class="radio address-verification-radio"
                        name="address-verification[<?php echo $type ?>]"
                        id="address-verification-skip-<?php echo $type ?>"
                        value="skip"
                        checked="checked"
                    />
                    <label class="address-verification-skip-<?php echo $type ?>"
                        for="address-verification-skip-<?php echo $type ?>">
                        <?php echo $this->__('Use entered address') ?>
                    </label>
                </li>
                <li>
                    <input type="radio" class="radio address-verification-radio"
                        name="address-verification[<?php echo $type ?>]"
                        id="address-verification-edit-<?php echo $type ?>"
                        value="edit"/>
                    <label for="address-verification-edit-<?php echo $type ?>">
                        <?php echo $this->__('Edit entered address') ?>
                    </label>
                </li>
                <?php if (!$validator->getAddressError($type)) : ?>
                    <?php foreach ($verifiedAddresses as $verifiedAddress) : ?>
                        <li>
                            <?php $idSuffix = md5(implode('_', $verifiedAddress)); ?>
                            <input type="radio" class="radio address-verification-radio"
                                name="address-verification[<?php echo $type ?>]"
                                id="address-verification-verified-<?php echo $type . '-' . $idSuffix ?>"
                                value="set"/>
                            <label for="address-verification-verified-<?php echo $type . '-' . $idSuffix ?>">
                                <?php echo $this->__('Use verified address') ?>:
                                <?php echo implode(' ', $verifiedAddress) ?>
                            </label>

                            <?php $fields = $this->getVerifiedAddressFields($verifiedAddress, $type); ?>
                            <?php foreach ($fields as $fieldName => $fieldValue) : ?>
                                <input class="input-verified" type="hidden"
                                    name="<?php echo $fieldName ?>"
                                    value="<?php echo $fieldValue ?>" />
                            <?php endforeach ?>
                        </li>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul>
        </div>
    <?php endforeach; ?>
    <div class="buttons-set">
        <button class="button verification-option address-verification-skip"><span><span><?php
            echo $this->__('Place order using selected option') ?></span></span></button>
        <button class="button verification-option address-verification-edit" style="display: none;"><span><span><?php
            echo $this->__('Edit address') ?></span></span></button>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
addressVerification = new FC.AddressVerification();
//]]>
</script>
